AccessTokenSettings:
  Algorithm: "RS512"
  SecretKey: "u_v-dRUIQcw3_nRlNeb7BS_5gOU4FVGHxSdVkOKP4IcBvpZQUL7j30T9TMMDKInLbZ7YQ7AUX4dhUVHgAI3Hz49EQP0q4GQ6_sFj4R6yvNq_lGxQAEHDbMaX-SCiXiji9Ceew_irf81rou-oE6HDL7LlfTiGHunQjdnBmaLoRpNZ_kFbk2fJagHPVsx0vgllcDTTb7FU0et9S6rjyfQIaTOTXwHuQ1AGtbtkhM6bJcuL5oiB8Ip6GIgqpxAJbcyQtPAj5so3sBJGQ1ntJ54J22o4TDh5LpEmX23X1lDuIWd-r1HbceLUERt9YptdcNB0oegcFZ6xp9LeuG_rzfPZXQ"
  Duration: "15m"
RefreshTokenSettings:
  Algorithm: "RS512"
  SecretKey: "ngQ-AP64-jAyClV7lMpJ0nt-xrk8v91hwdxRNz6TJhq03BqvdUmRfLgLoTnr8y0nyE_Bi_3_vVlaltUyzkkjKKl_rdXsfufMmwREy8RXCdkQyYuEqmXpMnNz51yb6v3uoXVfk4ONEsMQOWyXKLlFilDk9vBG1aQf-0WRX2w0mjs_CGt-BowzwSmDpa9samWYZmKu56VDe-QkIzWuk-3hHOLtFh7rNJRypRZ1C4edfzvWyGpAHtaaggcpihHrUPekTkCxTlXKhv2HRYJ92j6WlBAd2g4gn0O17i2pJH3rR0N_2wqz-SL4PuACVSGKZ_ybN8VQ--PxArXBq7cKMjP4-Q"
  Duration: "24h"